name: Kaggle CVE vulnerability enrichment automation pipeline

on:
    # Run automatically at 12:00 UTC every day
    schedule:
        - cron: '0 12 * * *'

    workflow_dispatch:
    # Run also when any of these files are updated using the GitHub UI (for testing)
    push:
        branches: 
            - main
        paths:
            - 'extract2.py'
            - 'kaggle_manager.py'
            - 'requirements.txt'
            - '.github/workflows/cve-pipeline.yml'

jobs:
    extract-cve-and-upload:
    
        runs-on: ubuntu-latest

        steps:
        #Step 1: Check out the repository 
        - name: Check repository
          uses: actions/checkout@v4





    
